"""
DPO Loss for SAM mask decoder (Paper Section 3.2, Formula 5).

4 candidate masks are generated by thresholding the reference model's sigmoid
output at [0.3, 0.4, 0.5, 0.6], ranked by IoU with GT, then used to compute
a preference-based loss that encourages the training model to favor
higher-IoU masks.

Key fix (v2): _log_prob only computes BCE on the "difference region" between
candidates, avoiding the signal dilution caused by mean-reducing over 65k
identical pixels.
"""

import logging
import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger(__name__)


class DPOLoss(nn.Module):

    THRESHOLDS = [0.3, 0.4, 0.5, 0.6]

    def __init__(self, beta1=1.0, beta2=0.5, temperature=1.0,
                 diagnose_batches=0, boundary_dilation=5):
        """
        Args:
            beta1, beta2: DPO reward weights for ranked candidates.
            temperature: temperature scaling for ref_logits before sigmoid.
                         T>1 makes the model less confident, creating more
                         uncertain pixels. T=1.0 means no scaling (default).
            diagnose_batches: if >0, print per-sample diagnostics for first N batches.
            boundary_dilation: dilation radius (pixels) for the difference region mask.
                               Expands the region where log_prob is computed beyond
                               the raw pixel differences between candidates.
        """
        super().__init__()
        self.beta1 = beta1
        self.beta2 = beta2
        self.temperature = temperature
        self.boundary_dilation = boundary_dilation
        self.diagnose_batches = diagnose_batches
        self._diag_count = 0

    @staticmethod
    def _iou(pred, gt):
        intersection = (pred * gt).sum()
        union = pred.sum() + gt.sum() - intersection
        return intersection / (union + 1e-7)

    @staticmethod
    def _masked_log_prob(logits, binary_mask, region_mask):
        """Compute log_prob only on pixels where region_mask=1."""
        bce_per_pixel = F.binary_cross_entropy_with_logits(
            logits, binary_mask, reduction="none"
        )
        masked_bce = bce_per_pixel * region_mask
        n_pixels = region_mask.sum().clamp(min=1)
        return -(masked_bce.sum() / n_pixels)

    @staticmethod
    def _log_prob(logits, binary_mask):
        """Full-image log_prob (kept for diagnostics comparison)."""
        return -F.binary_cross_entropy_with_logits(
            logits, binary_mask, reduction="mean"
        )

    def _build_region_mask(self, candidates):
        """Build a binary mask covering all pixels that differ across candidates,
        dilated by self.boundary_dilation to include nearby context."""
        union_diff = torch.zeros_like(candidates[0])
        for i in range(len(candidates)):
            for j in range(i + 1, len(candidates)):
                union_diff = torch.max(union_diff, (candidates[i] - candidates[j]).abs())

        if self.boundary_dilation > 0:
            k = 2 * self.boundary_dilation + 1
            kernel = torch.ones(1, 1, k, k, device=union_diff.device)
            dilated = F.conv2d(
                union_diff.unsqueeze(0), kernel, padding=self.boundary_dilation
            )
            union_diff = (dilated.squeeze(0) > 0).float()

        return union_diff

    def forward(self, current_logits, ref_logits, gt_mask):
        """
        Args:
            current_logits: (B, 1, H, W) training model mask logits
            ref_logits:     (B, 1, H, W) frozen reference model mask logits
            gt_mask:        (B, 1, H, W) ground truth binary mask
        Returns:
            scalar DPO loss
        """
        B = current_logits.shape[0]
        scaled_ref = ref_logits / self.temperature
        ref_probs = torch.sigmoid(scaled_ref)
        do_diag = self._diag_count < self.diagnose_batches

        total_loss = torch.tensor(0.0, device=current_logits.device)
        valid_count = 0

        for b in range(B):
            cur = current_logits[b]  # (1, H, W)
            ref = ref_logits[b]
            gt = gt_mask[b]

            candidates = [(ref_probs[b] > t).float() for t in self.THRESHOLDS]
            ious = [self._iou(c, gt) for c in candidates]
            order = sorted(range(4), key=lambda i: ious[i], reverse=True)
            ranked = [candidates[order[i]] for i in range(4)]

            region_mask = self._build_region_mask(candidates)
            n_region = region_mask.sum().item()

            if do_diag:
                rp = ref_probs[b]
                n_pixels = rp.numel()
                n_uncertain = ((rp > 0.3) & (rp < 0.6)).sum().item()
                pairwise_diff = []
                for i in range(4):
                    for j in range(i + 1, 4):
                        diff = (candidates[i] - candidates[j]).abs().sum().item()
                        pairwise_diff.append(f"c{i}-c{j}={int(diff)}")
                logger.info(
                    f"[DIAG batch={self._diag_count} sample={b}] "
                    f"T={self.temperature} "
                    f"sigmoid range=[{rp.min():.4f}, {rp.max():.4f}] "
                    f"uncertain(0.3~0.6)={n_uncertain}/{n_pixels} ({100*n_uncertain/n_pixels:.2f}%) | "
                    f"region_mask_pixels={int(n_region)}/{n_pixels} ({100*n_region/n_pixels:.2f}%) | "
                    f"IoU: t0.3={ious[0]:.4f} t0.4={ious[1]:.4f} t0.5={ious[2]:.4f} t0.6={ious[3]:.4f} | "
                    f"order={[self.THRESHOLDS[o] for o in order]} | "
                    f"diffs: {', '.join(pairwise_diff)} | "
                    f"skipped={'YES' if ious[order[0]] == ious[order[3]] else 'NO'}"
                )

            if ious[order[0]] == ious[order[3]]:
                continue

            if n_region < 1:
                continue

            log_ratios = []
            for mask in ranked:
                lr = (self._masked_log_prob(cur, mask, region_mask)
                      - self._masked_log_prob(ref, mask, region_mask))
                log_ratios.append(lr)

            reward = (
                self.beta1 * log_ratios[0]
                + self.beta2 * log_ratios[1]
                - self.beta2 * log_ratios[2]
                - self.beta1 * log_ratios[3]
            )

            if do_diag:
                logger.info(
                    f"  [DIAG] log_ratios={[f'{lr.item():.6f}' for lr in log_ratios]} "
                    f"reward={reward.item():.6f} loss={(-F.logsigmoid(reward)).item():.6f}"
                )

            total_loss += -F.logsigmoid(reward)
            valid_count += 1

        if do_diag:
            self._diag_count += 1
            logger.info(
                f"[DIAG batch={self._diag_count - 1}] "
                f"valid={valid_count}/{B} "
                f"avg_loss={total_loss.item() / max(valid_count, 1):.6f}"
            )

        if valid_count == 0:
            return torch.tensor(0.0, device=current_logits.device, requires_grad=True)

        return total_loss / valid_count
